name: machineLearningCancerClassification
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7.1
  - matplotlib
  # Core scientific python
  - numpy
  - scikit-learn
  - seaborn
  - tensorflow